# Generated by Django 2.2.16 on 2021-01-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210121_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_active',
            new_name='is_published',
        ),
    ]
