# Generated by Django 2.2.16 on 2021-02-25 09:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210204_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='synopsis',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='synopsis'),
            preserve_default=False,
        ),
    ]
