# Generated by Django 2.2.16 on 2021-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hagakure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersbio',
            name='photo',
            field=models.ImageField(upload_to='members/'),
        ),
    ]
