# Generated by Django 2.2.16 on 2021-01-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='weekdays',
        ),
        migrations.AddField(
            model_name='training',
            name='weekdays',
            field=models.ManyToManyField(to='trainings.Weekday'),
        ),
    ]
