# Generated by Django 2.2.16 on 2021-01-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='lentght',
            new_name='lenght',
        ),
    ]
