# Generated by Django 2.2.16 on 2021-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_trainerbio'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerbio',
            name='disciplines',
            field=models.ManyToManyField(to='trainings.Discipline'),
        ),
    ]
