# Generated by Django 2.2.16 on 2021-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20210128_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerbio',
            name='photo',
            field=models.ImageField(upload_to='trainers'),
        ),
    ]
